version: '3'

# list of all containers you intended to be used
services:
    
    ################################################################################
    # run tweet_collector container
    ################################################################################

    tweet_collector:                       
        build: tweet_collector/
        # image gets created from Dockerfile   
        volumes: 
        # creating local dir into the "/tweet_collector"-dir in this container
        - ./tweet_collector/:/tweet_collector/
        depends_on:
        # DB into which tweets are dumped                
        - mongodb
        env_file:
        - .env

    ################################################################################   
     # fire up MongoDB container
     ###############################################################################
    
    mongodb:                           
        image: mongo
        # image downloaded from Docker Hub                   
        ports:
        # maps port 27017 of this container (RS) to port 27017 of localhost (LS)
        - 27017:27017             
    
    ################################################################################
    # run etl_job container 
    ################################################################################
    
    etl_job:                         
        build: etl_job/
        # image gets created from Dockerfile
        # platform:--platform linux/amd64 should be added if problem for Mac
        volumes:
         # creating local dir into the "/etl"-dir in this container
        - ./etl_job/:/etl/      
        depends_on:
        - mongodb           # DB from which we extract tweets                     
        - postgresdb        # DB into which we load transformed tweets
    
    ################################################################################
    # fire up postgresDB container 
    ################################################################################

    postgresdb:                    
        image: postgres
        # image downloaded from Docker Hub               
        ports:
        # maps port 5432 of this container (RS) to port 5555 of localhost (LS)
        - 5555:5432         
        environment:
        # sets environment variables                 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=tweets
    
    ################################################################################
    # finally, the cherry on top: slackbot container
    ################################################################################
    
    slackbot:                       
        build: slackbot/
        volumes:
        - ./slackbot/:/post_tweet/
        depends_on:
        - postgresdb
        env_file:
        - .env

    ################################################################################
    #
    ################################################################################